USE SeicenToolsDB;
CREATE TABLE Utente(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(70) NOT NULL UNIQUE,
	ruolo VARCHAR(20) NOT NULL,
    hashPwd VARCHAR(255) NOT NULL
);

CREATE TABLE Prodotto(
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	categoria VARCHAR(50) NOT NULL,
	descrizione VARCHAR(255),
	prezzo DECIMAL(10, 2) NOT NULL,
	imgPath VARCHAR(255),
	disponibilita INT NOT NULL
);

CREATE TABLE Ordine(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	id_utente INT NOT NULL,
	tot DECIMAL (10, 2),
	qta INT NOT NULL,
    numCarta VARCHAR(12) NOT NULL,
	dataCreazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	indirizzoConsegna VARCHAR(255) NOT NULL,
	FOREIGN KEY (id_utente) REFERENCES Utente(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ProdottiOrdinati(
	id INT AUTO_INCREMENT PRIMARY KEY,
    id_prodotto INT,
    id_ordine INT NOT NULL,
    
    FOREIGN KEY (id_prodotto) REFERENCES Prodotto(id) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (id_ordine) REFERENCES Ordine(id) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE CarrelloUtente(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    id_utente INT NOT NULL,
    id_prodotto INT,
    
    FOREIGN KEY (id_prodotto) REFERENCES Prodotto(id) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (id_utente) REFERENCES Utente(id) ON UPDATE CASCADE ON DELETE CASCADE
);
